In [10]:
import numpy as np

In [11]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.shape)

arr2 = np.array([[1, 2, 3, 4, 5]])
print(arr2)
print(arr2.shape)

print(arr2.reshape(5,1))
print(arr2.reshape(5,1).shape)

print(arr2.reshape(1,5))
print(arr2.reshape(1,5).shape)

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]]
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)
[[1 2 3 4 5]]
(1, 5)


In [12]:
print('Array',' ' ,arr2)
print('Shape',' ' ,arr2.shape)
print('No of dimensions',' ' ,arr2.ndim)
print('No of elements',' ' ,arr2.size)
print('datatype',' ' ,arr2.dtype)
print('size in bytes',' ' ,arr2.itemsize)

Array   [[1 2 3 4 5]]
Shape   (1, 5)
No of dimensions   2
No of elements   5
datatype   int64
size in bytes   8


In [15]:
## vectorized functions are element wise

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

addition = a + b
subtraction = a - b
multiplication = a*b
division = a/b

print('Addition ', addition)
print('Subtraction ', subtraction)
print('Multiplication ', multiplication)
print('Division ', division)

Addition  [11 22 33 44]
Subtraction  [ 9 18 27 36]
Multiplication  [ 10  40  90 160]
Division  [10. 10. 10. 10.]


In [17]:
arr = np.array([1,2,3])

print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


In [34]:
arr = np.array(
[[1,2,3], 
[4,5,6], 
[7, 8, 9]]
)


# selection

print(arr[1][2])
print(arr[1, 2])


# slicing

print(arr[1:,2:]) 

print(arr[0:2, 0:])


6
6
[[6]
 [9]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# logical ops

data = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(data > 5)
print((data>=5) & (data<8))

[False False False False False  True  True  True]
[False False False False  True  True  True False]
